[package]
name = "mlx5cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbg_hex = "0.2.0"
libc = "0.2.153"
pci-driver = "0.1.4"
thiserror = "1.0.58"
